import { CandidateProfile, JobPost } from "./types";

export const defaultProfile: CandidateProfile = {
  education: "本科",
  degree: "学士",
  major: "计算机科学与技术",
  graduationYear: "2026",
  politicalStatus: "共青团员",
  household: "广东",
  hometown: "广东",
  grassrootsYears: "0",
  serviceProject: false,
  examScope: "全部",
  regions: ["广东", "北京"],
  preference: "综合推荐",
};

export const jobPosts: JobPost[] = [
  {
    id: "gz-tax-001",
    exam: "国考",
    agency: "国家税务总局广州市天河区税务局",
    title: "一级行政执法员",
    region: "广东",
    city: "广州",
    level: "市区机关",
    hires: 3,
    educationRequirement: ["本科", "硕士", "博士"],
    degreeRequirement: ["学士", "硕士", "博士"],
    majorRequirements: ["计算机", "电子信息", "软件工程"],
    politicalRequirement: "不限",
    grassrootsYears: 0,
    serviceProjectRequired: false,
    description: "负责税收征管系统维护、数据治理和基层执法辅助工作。",
    history: [
      { year: 2021, hires: 2, applicants: 246, competitionRatio: 123, interviewScore: 129.8, admissionScore: 134.2 },
      { year: 2022, hires: 3, applicants: 318, competitionRatio: 106, interviewScore: 128.1, admissionScore: 133.5 },
      { year: 2023, hires: 3, applicants: 351, competitionRatio: 117, interviewScore: 130.4, admissionScore: 135.1 },
      { year: 2024, hires: 4, applicants: 396, competitionRatio: 99, interviewScore: 127.6, admissionScore: 132.8 },
      { year: 2025, hires: 3, applicants: 372, competitionRatio: 124, interviewScore: 131.2, admissionScore: 136.4 },
    ],
  },
  {
    id: "bj-miit-002",
    exam: "国考",
    agency: "工业和信息化部信息中心",
    title: "综合管理岗",
    region: "北京",
    city: "北京",
    level: "中央机关直属单位",
    hires: 2,
    educationRequirement: ["硕士", "博士"],
    degreeRequirement: ["硕士", "博士"],
    majorRequirements: ["计算机", "信息管理", "网络安全"],
    politicalRequirement: "中共党员",
    grassrootsYears: 0,
    serviceProjectRequired: false,
    description: "参与政务信息化项目管理、数据安全评估和政策研究支撑。",
    history: [
      { year: 2021, hires: 1, applicants: 188, competitionRatio: 188, interviewScore: 136.5, admissionScore: 140.3 },
      { year: 2022, hires: 2, applicants: 268, competitionRatio: 134, interviewScore: 134.7, admissionScore: 139.6 },
      { year: 2023, hires: 2, applicants: 331, competitionRatio: 166, interviewScore: 137.8, admissionScore: 142.2 },
      { year: 2024, hires: 1, applicants: 240, competitionRatio: 240, interviewScore: 139.4, admissionScore: 143.5 },
      { year: 2025, hires: 2, applicants: 358, competitionRatio: 179, interviewScore: 138.9, admissionScore: 143.1 },
    ],
  },
  {
    id: "sz-market-003",
    exam: "省考",
    agency: "深圳市市场监督管理局南山监管所",
    title: "数字监管岗",
    region: "广东",
    city: "深圳",
    level: "基层执法",
    hires: 4,
    educationRequirement: ["本科", "硕士", "博士"],
    degreeRequirement: ["学士", "硕士", "博士"],
    majorRequirements: ["计算机", "法学", "电子商务"],
    politicalRequirement: "不限",
    grassrootsYears: 0,
    serviceProjectRequired: false,
    description: "负责市场主体数字化监管、投诉数据分析和一线执法协同。",
    history: [
      { year: 2021, hires: 3, applicants: 420, competitionRatio: 140, interviewScore: 72.4, admissionScore: 76.1 },
      { year: 2022, hires: 4, applicants: 388, competitionRatio: 97, interviewScore: 70.8, admissionScore: 74.9 },
      { year: 2023, hires: 5, applicants: 465, competitionRatio: 93, interviewScore: 69.6, admissionScore: 73.8 },
      { year: 2024, hires: 4, applicants: 510, competitionRatio: 128, interviewScore: 72.9, admissionScore: 76.4 },
      { year: 2025, hires: 4, applicants: 476, competitionRatio: 119, interviewScore: 71.7, admissionScore: 75.6 },
    ],
  },
  {
    id: "gd-audit-004",
    exam: "省考",
    agency: "广东省审计厅",
    title: "数据审计岗",
    region: "广东",
    city: "广州",
    level: "省直机关",
    hires: 2,
    educationRequirement: ["本科", "硕士", "博士"],
    degreeRequirement: ["学士", "硕士", "博士"],
    majorRequirements: ["会计学", "审计学", "计算机", "统计学"],
    politicalRequirement: "不限",
    grassrootsYears: 0,
    serviceProjectRequired: false,
    description: "从事财政资金、重大项目和公共数据的审计分析工作。",
    history: [
      { year: 2021, hires: 2, applicants: 164, competitionRatio: 82, interviewScore: 71.2, admissionScore: 74.5 },
      { year: 2022, hires: 2, applicants: 192, competitionRatio: 96, interviewScore: 72.5, admissionScore: 75.3 },
      { year: 2023, hires: 2, applicants: 230, competitionRatio: 115, interviewScore: 73.1, admissionScore: 76.7 },
      { year: 2024, hires: 3, applicants: 258, competitionRatio: 86, interviewScore: 71.8, admissionScore: 75.0 },
      { year: 2025, hires: 2, applicants: 236, competitionRatio: 118, interviewScore: 73.6, admissionScore: 77.1 },
    ],
  },
  {
    id: "hz-civil-005",
    exam: "省考",
    agency: "杭州市民政局",
    title: "基层治理岗",
    region: "浙江",
    city: "杭州",
    level: "市直机关",
    hires: 1,
    educationRequirement: ["本科", "硕士", "博士"],
    degreeRequirement: ["学士", "硕士", "博士"],
    majorRequirements: ["社会学", "公共管理", "法学", "不限"],
    politicalRequirement: "不限",
    grassrootsYears: 2,
    serviceProjectRequired: false,
    description: "负责基层治理、社会组织管理和民生服务项目统筹。",
    history: [
      { year: 2021, hires: 1, applicants: 96, competitionRatio: 96, interviewScore: 73.3, admissionScore: 76.8 },
      { year: 2022, hires: 1, applicants: 122, competitionRatio: 122, interviewScore: 74.8, admissionScore: 78.1 },
      { year: 2023, hires: 1, applicants: 136, competitionRatio: 136, interviewScore: 75.2, admissionScore: 78.4 },
      { year: 2024, hires: 2, applicants: 146, competitionRatio: 73, interviewScore: 72.1, admissionScore: 75.5 },
      { year: 2025, hires: 1, applicants: 118, competitionRatio: 118, interviewScore: 74.0, admissionScore: 77.6 },
    ],
  },
  {
    id: "cq-town-006",
    exam: "省考",
    agency: "重庆市璧山区乡镇机关",
    title: "综合管理岗",
    region: "重庆",
    city: "重庆",
    level: "乡镇机关",
    hires: 5,
    educationRequirement: ["专科", "本科", "硕士", "博士"],
    degreeRequirement: ["无", "学士", "硕士", "博士"],
    majorRequirements: ["不限"],
    politicalRequirement: "不限",
    grassrootsYears: 0,
    serviceProjectRequired: true,
    description: "面向服务基层项目人员，承担乡镇综合治理和公共服务工作。",
    history: [
      { year: 2021, hires: 4, applicants: 108, competitionRatio: 27, interviewScore: 66.2, admissionScore: 69.4 },
      { year: 2022, hires: 5, applicants: 135, competitionRatio: 27, interviewScore: 65.8, admissionScore: 68.9 },
      { year: 2023, hires: 6, applicants: 174, competitionRatio: 29, interviewScore: 66.7, admissionScore: 70.1 },
      { year: 2024, hires: 5, applicants: 160, competitionRatio: 32, interviewScore: 67.4, admissionScore: 70.6 },
      { year: 2025, hires: 5, applicants: 148, competitionRatio: 30, interviewScore: 66.9, admissionScore: 70.2 },
    ],
  },
  {
    id: "sh-police-007",
    exam: "省考",
    agency: "上海市公安局",
    title: "信息通信岗",
    region: "上海",
    city: "上海",
    level: "市直机关",
    hires: 6,
    educationRequirement: ["本科", "硕士", "博士"],
    degreeRequirement: ["学士", "硕士", "博士"],
    majorRequirements: ["计算机", "通信工程", "网络安全"],
    politicalRequirement: "不限",
    grassrootsYears: 0,
    serviceProjectRequired: false,
    description: "负责公安信息通信、网络安全保障和系统运行维护。",
    history: [
      { year: 2021, hires: 5, applicants: 315, competitionRatio: 63, interviewScore: 68.6, admissionScore: 72.3 },
      { year: 2022, hires: 5, applicants: 352, competitionRatio: 70, interviewScore: 69.2, admissionScore: 73.0 },
      { year: 2023, hires: 6, applicants: 390, competitionRatio: 65, interviewScore: 68.8, admissionScore: 72.8 },
      { year: 2024, hires: 6, applicants: 426, competitionRatio: 71, interviewScore: 69.5, admissionScore: 73.4 },
      { year: 2025, hires: 6, applicants: 408, competitionRatio: 68, interviewScore: 69.1, admissionScore: 73.2 },
    ],
  },
];
